runtime: python310

entrypoint: gunicorn -b :$PORT wsgi:application

instance_class: F2

env_variables:
  DJANGO_SETTINGS_MODULE: "settings"
  GOOGLE_CLOUD_PROJECT: "143642567909"
  SECRET_KEY: "@GOOGLE_SECRET:dj-secret"
  YELP_API_KEY: "@GOOGLE_SECRET:YELP_API_KEY"
  DEBUG: "False"
  ALLOWED_HOSTS: "hirebrianmaclin.com,127.0.0.1"

handlers:
  - url: /static
    static_dir: staticfiles/

  - url: /.*
    script: auto

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5
