services:
  web:
    image: bmaclin58/personal-portfolio
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
    command: gunicorn --bind 0.0.0.0:8080 wsgi:application
