"""
Django settings for DermaLytica project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
import environ
from dotenv import load_dotenv
from urllib.parse import urlparse

from GemmaJudge.services.config import (
    build_required_setting_names,
    normalize_storage_path,
    validate_required_settings,
)

# ------------------------------------------------------------------------
#                 .Env Secret Variables / Path Building
# ------------------------------------------------------------------------

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent


def get_secret(secret_name):
    """Try GCP Secret Manager as a fallback when local env vars are absent."""
    local_value = os.getenv(secret_name)
    if local_value:
        return local_value

    try:
        from google.cloud import secretmanager
    except Exception:
        return None

    project_id = os.getenv("GCP_PROJECT_ID")
    client = secretmanager.SecretManagerServiceClient()
    name = f"projects/{project_id}/secrets/{secret_name}/versions/latest"
    try:
        response = client.access_secret_version(name=name)
        return response.payload.data.decode("UTF-8")
    except Exception:
        return None # Ensure application doesn't crash

env_file = os.path.join(BASE_DIR, ".env")

if os.path.isfile(env_file):
	# Use a local secret file, if provided
	load_dotenv()
	SECRET_KEY = os.getenv("DJANGO_KEY")
	MAPS_API_KEY = os.getenv("MAPS_API_KEY")

else:
	# Pull secrets from Secret Manager
	SECRET_KEY = get_secret("djangoSettings")
	MAPS_API_KEY = get_secret("MAPS_API_KEY")

os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'

DEBUG = False

ALLOWED_HOSTS = ['dermalytica-143642567909.us-central1.run.app', 'hirebrianmaclin.com']
CSRF_TRUSTED_ORIGINS = [
    'https://dermalytica-143642567909.us-central1.run.app',
    'https://hirebrianmaclin.com',
    'https://*.hirebrianmaclin.com'
]


# Application definition

INSTALLED_APPS = [
		'whitenoise.runserver_nostatic',
		'crispy_forms',
		"crispy_bootstrap5",
		'django.contrib.admin',
		'django.contrib.auth',
		'django.contrib.contenttypes',
		'django.contrib.sessions',
		'django.contrib.messages',
		'django.contrib.staticfiles',
		'DermaLytica.apps.DermaLyticaConfig',
		'Home_Portfolio.apps.HomePortfolioConfig',
		'Clarissa.apps.ClarissaConfig',
		'BullyFilter.apps.BullyFilterConfig',
		'GemmaJudge.apps.GemmaJudgeConfig',
		]

MIDDLEWARE = [
		'django.middleware.security.SecurityMiddleware',
		'whitenoise.middleware.WhiteNoiseMiddleware',
		'django.contrib.sessions.middleware.SessionMiddleware',
		'django.middleware.common.CommonMiddleware',
		'django.middleware.csrf.CsrfViewMiddleware',
		'django.contrib.auth.middleware.AuthenticationMiddleware',
		'django.contrib.messages.middleware.MessageMiddleware',
		'django.middleware.clickjacking.XFrameOptionsMiddleware',
		]

ROOT_URLCONF = 'urls'

TEMPLATES = [
		{
				'BACKEND':  'django.template.backends.django.DjangoTemplates',
				'DIRS':     [BASE_DIR / 'templates'],
				'APP_DIRS': True,
				'OPTIONS':  {
						'context_processors': [
								'django.template.context_processors.debug',
								'django.template.context_processors.request',
								'django.contrib.auth.context_processors.auth',
								'django.contrib.messages.context_processors.messages',
								],
						},
				},
		]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

#WSGI_APPLICATION = 'wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
		{
				'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
				},
		{
				'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
				},
		{
				'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
				},
		{
				'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
				},
		]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "America/New_York"

USE_I18N = True

USE_TZ = True

# ------------------------------------------------------------------------
#          Static / Media files (CSS, JavaScript, Images, Docs)
#        https://docs.djangoproject.com/en/5.1/howto/static-files/
# ------------------------------------------------------------------------

STATIC_URL = "/staticfiles/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles/')
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "/Files/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

GEMMA_JUDGE_MOUNTED_DUCKDB_PATH = normalize_storage_path(os.getenv("GEMMA_JUDGE_MOUNTED_DUCKDB_PATH"))
GEMMA_JUDGE_MOUNTED_CHROMA_DIR = normalize_storage_path(os.getenv("GEMMA_JUDGE_MOUNTED_CHROMA_DIR"))
GEMMA_JUDGE_MOUNTED_EMBEDDING_MODEL_DIR = normalize_storage_path(os.getenv("GEMMA_JUDGE_MOUNTED_EMBEDDING_MODEL_DIR"))

_raw_gemma_settings = {
    "GEMMA_JUDGE_ENDPOINT": get_secret("GEMMA_JUDGE_ENDPOINT"),
    "CLD_USER": get_secret("CLD_USER"),
    "HMAC_K": get_secret("HMAC_K"),
    "DUCKDB_PATH": get_secret("DUCKDB_PATH"),
    "CHROMA_DB_PATH": get_secret("CHROMA_DB_PATH"),
    "LOCAL_EMBEDDING_MODEL_PATH": get_secret("LOCAL_EMBEDDING_MODEL_PATH"),
}
_gemma_settings = validate_required_settings(
    _raw_gemma_settings,
    required_keys=build_required_setting_names(
        mounted_duckdb_path=GEMMA_JUDGE_MOUNTED_DUCKDB_PATH,
        mounted_chroma_dir=GEMMA_JUDGE_MOUNTED_CHROMA_DIR,
        mounted_embedding_model_dir=GEMMA_JUDGE_MOUNTED_EMBEDDING_MODEL_DIR,
    ),
)
GEMMA_JUDGE_SYNC_ON_STARTUP = os.getenv("GEMMA_JUDGE_SYNC_ON_STARTUP", "true").lower() == "true"
GEMMA_JUDGE_ENDPOINT = _gemma_settings["GEMMA_JUDGE_ENDPOINT"]
GEMMA_JUDGE_MODEL = os.getenv("GEMMA_JUDGE_MODEL", "google/gemma-4-31b-it")

CLD_USER = _gemma_settings["CLD_USER"]
HMAC_K = _gemma_settings["HMAC_K"]

GEMMA_JUDGE_DUCKDB_PATH = GEMMA_JUDGE_MOUNTED_DUCKDB_PATH or normalize_storage_path(_raw_gemma_settings.get("DUCKDB_PATH"))
GEMMA_JUDGE_CHROMA_DB_PATH = GEMMA_JUDGE_MOUNTED_CHROMA_DIR or normalize_storage_path(
    _raw_gemma_settings.get("CHROMA_DB_PATH")
)
GEMMA_JUDGE_LOCAL_EMBEDDING_MODEL_PATH = (
    GEMMA_JUDGE_MOUNTED_EMBEDDING_MODEL_DIR
    or normalize_storage_path(_raw_gemma_settings.get("LOCAL_EMBEDDING_MODEL_PATH"))
)

GEMMA_JUDGE_MAX_TOKENS_QUICK = int(os.getenv("GEMMA_JUDGE_MAX_TOKENS_QUICK"))
GEMMA_JUDGE_MAX_TOKENS_THINKING = int(os.getenv("GEMMA_JUDGE_MAX_TOKENS_THINKING"))

_runtime_cache_dir = normalize_storage_path(os.getenv("GEMMA_JUDGE_RUNTIME_CACHE_DIR")) or str(
    BASE_DIR / ".runtime_cache" / "gemma_judge"
)
GEMMA_JUDGE_RUNTIME_CACHE_DIR = Path(_runtime_cache_dir)
GEMMA_JUDGE_LOCAL_CHROMA_DIR = GEMMA_JUDGE_RUNTIME_CACHE_DIR / "mtg_rules_chromadb"
GEMMA_JUDGE_LOCAL_EMBEDDING_MODEL_DIR = GEMMA_JUDGE_RUNTIME_CACHE_DIR / "embedding_model"
